/**
 * PearTree Core API Integration
 * Handles communication with the backend planner service
 */

// Use local API endpoint for now, will switch to PearTree Core when ready
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || '/api';

export interface PlannerRequest {
  location: string;
  duration: number; // in days
  type: 'trekking' | 'family' | 'bike' | 'relaks' | 'aktywnie';
  startDate?: string;
}

export interface RouteStop {
  id: string;
  name: string;
  type: 'parking' | 'attraction' | 'peak' | 'restaurant' | 'accommodation';
  lat: number;
  lng: number;
  time?: string;
  duration?: number; // minutes
  description?: string;
}

export interface RouteStats {
  distance: number; // km
  duration: number; // hours
  elevation: number; // meters
  difficulty: 'easy' | 'moderate' | 'hard';
}

export interface WeatherInfo {
  temp: number;
  condition: string;
  icon: string;
  alert?: string;
}

export interface PlannerResponse {
  id: string;
  route: {
    path: [number, number][]; // [lat, lng][]
    stops: RouteStop[];
  };
  stats: RouteStats;
  weather: WeatherInfo;
  listings: {
    accommodations: string[];
    restaurants: string[];
    attractions: string[];
  };
  aiPlanReady: boolean;
  aiPlanId?: string;
}

export interface AIPlanResponse {
  planId: string;
  timeline: {
    time: string;
    activity: string;
    location: string;
    notes?: string;
  }[];
  recommendations: string[];
  tips: string[];
}

/**
 * Generate a travel plan
 */
export async function generatePlan(request: PlannerRequest): Promise<PlannerResponse> {
  const response = await fetch(`${API_BASE}/planner`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(request),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: 'Failed to generate plan' }));
    throw new Error(error.message || 'Failed to generate plan');
  }

  return response.json();
}

/**
 * Fetch AI-generated plan details (async polling)
 */
export async function fetchAIPlan(planId: string): Promise<AIPlanResponse | null> {
  const response = await fetch(`${API_BASE}/planner/ai/${planId}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (response.status === 202) {
    // AI plan not ready yet
    return null;
  }

  if (!response.ok) {
    throw new Error('Failed to fetch AI plan');
  }

  return response.json();
}

/**
 * Export plan as GPX file
 */
export function exportGPX(route: { path: [number, number][]; stops: RouteStop[] }, planName: string): string {
  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Beskidzku.pl" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${planName}</name>
    <desc>Generated by Beskidzku.pl Planner</desc>
  </metadata>
  <trk>
    <name>${planName}</name>
    <trkseg>
${route.path.map(([lat, lng]) => `      <trkpt lat="${lat}" lon="${lng}"></trkpt>`).join('\n')}
    </trkseg>
  </trk>
${route.stops.map(stop => `  <wpt lat="${stop.lat}" lon="${stop.lng}">
    <name>${stop.name}</name>
    <desc>${stop.description || stop.type}</desc>
    <type>${stop.type}</type>
  </wpt>`).join('\n')}
</gpx>`;

  return gpx;
}

/**
 * Download GPX file to user's device
 */
export function downloadGPX(gpxContent: string, filename: string): void {
  const blob = new Blob([gpxContent], { type: 'application/gpx+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.gpx') ? filename : `${filename}.gpx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Build Google Maps URL from route
 */
export function buildGoogleMapsUrl(stops: RouteStop[]): string {
  if (stops.length === 0) return 'https://maps.google.com';

  if (stops.length === 1) {
    return `https://www.google.com/maps/search/?api=1&query=${stops[0].lat},${stops[0].lng}`;
  }

  const origin = `${stops[0].lat},${stops[0].lng}`;
  const destination = `${stops[stops.length - 1].lat},${stops[stops.length - 1].lng}`;
  const waypoints = stops
    .slice(1, -1)
    .map(s => `${s.lat},${s.lng}`)
    .join('|');

  let url = `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}`;
  if (waypoints) {
    url += `&waypoints=${encodeURIComponent(waypoints)}`;
  }
  url += '&travelmode=driving';

  return url;
}
